"""empty message

Revision ID: 5e76716b05ea
Revises: ca766e3baf57
Create Date: 2017-12-26 20:03:18.590981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e76716b05ea'
down_revision = 'ca766e3baf57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u'nextval(\'"Users_id_seq"\'::regclass)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'Users_pkey')
    )
    op.drop_table('users')
    # ### end Alembic commands ###
